services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8005:80"
    networks:
      - hummingbird
      - shared-network
    depends_on:
      - php

  php:
    build: docker/.
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    networks:
      - hummingbird
      - shared-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - hummingbird
      - shared-network
    expose:
      - "5432"  # доступен только в сети docker, не наружу

networks:
  hummingbird:
    driver: bridge
  shared-network:
    external: true  # используем внешнюю сеть
volumes:
  postgres_data: